#!/usr/bin/env tsx
/**
 * Build-time generation of the landing page's ASCII hero banner (§3.5/E3):
 * large "CCGM" lettering, hand-authored here rather than pulled from a
 * figlet dependency -- five fixed lines of block lettering is the simplest
 * implementation that fully meets the requirement, and adds no runtime or
 * build dependency for a one-time static string.
 *
 * Output: src/generated/banner.txt (gitignored, like the rest of
 * src/generated/ -- regenerated by every build). AsciiArt.astro reads this
 * file as its default `art` content when a page does not pass its own.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const BANNER_LINES = [
  ' ██████╗ ██████╗ ██████╗ ███╗   ███╗',
  '██╔════╝██╔════╝██╔════╝ ████╗ ████║',
  '██║     ██║     ██║  ███╗██╔████╔██║',
  '██║     ██║     ██║   ██║██║╚██╔╝██║',
  '╚██████╗╚██████╗╚██████╔╝██║ ╚═╝ ██║',
  ' ╚═════╝ ╚═════╝ ╚═════╝ ╚═╝     ╚═╝',
];

/** Deterministic banner text -- same output on every call, every run. */
export function buildBanner(): string {
  return BANNER_LINES.join('\n');
}

const scriptDir = fileURLToPath(new URL('.', import.meta.url));
const repoRoot = join(scriptDir, '..');
const outPath = join(repoRoot, 'src', 'generated', 'banner.txt');

export function writeBanner(path: string = outPath): void {
  const dir = dirname(path);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }
  writeFileSync(path, buildBanner());
}

function main(): void {
  writeBanner();
  const written = readFileSync(outPath, 'utf-8');
  console.log(`ascii-banner: wrote ${outPath} (${written.split('\n').length} lines)`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  main();
}
